### PR TITLE
Add some styled components

### PR DESCRIPTION
**Pull request by johnsonkwok**
Hey @wusihong , can you please review my PR when you have the time? I've added some styled components to start getting parts of my module to resemble Airbnb's website.

### CODE REVIEW

**Comment by johnsonkwok** [comment]
FYI, this PR is mainly related to the addition of styled components. I haven't implemented functionality or proper rendering for my Book component yet (which includes Guests and Dates as child components). Let me know if anything's unclear.

**Comment by johnsonkwok** [comment]
Hey @mariomui , could you take a quick look at my PR here? I've assigned it to both you and ed depending on whoever has time to take a look at it first.

**Comment by mariomui** [comment]
I'll be taking this ticket

**Review by mariomui — COMMENTED** [review]
If you wrap your entire styled components with a module exports
module.exports = { 
x: y 
}
you could skip the step of exporting the bottom stuff
so when you call it 
Within the component that actually uses the style, you can do import {x} from styledcomponentsstorage.

**Review by mariomui — COMMENTED** [review]
If you wrap your entire styled components with a module exports
module.exports = {
x: y
}
you could skip the step of exporting the bottom stuff
so when you call it
Within the component that actually uses the style, you can do import {x} from styledcomponentsstorage.

**Comment by johnsonkwok** [comment]
> If you wrap your entire styled components with a module exports
> module.exports = {
> x: y
> }
> you could skip the step of exporting the bottom stuff
> so when you call it
> Within the component that actually uses the style, you can do import {x} from 
> styledcomponentsstorage.

Thanks for the review, mario. You're right, it was getting pretty inconvenient to keep having to add to the ever-growing exports object at the bottom of the styled components file. I am removing that in a subsequent PR.

**Pull request merged**
