### PR TITLE
Revise code for seeding db and Implement server code for GET request

### PR DESCRIPTION
**Pull request by johnsonkwok**

### CODE REVIEW

**Comment by mariomui** [comment]
Please atomicize your pull requests so I know which commits are for which area.

**Review by mariomui — APPROVED** [review]

**Review by mariomui — APPROVED** [review]
just talked with you, you do have a catch for your errors so everything is okay.
If possible, limit the lines to 20-30 so it's not as long per line.

**Review by mariomui — APPROVED** [review]

**Review by mariomui — CHANGES_REQUESTED** [review]
Maybe a more specific name for RoomData, because pictures is room data but you dont have that. etc etc.

**Comment by johnsonkwok** [comment]
> Please atomicize [itemize] your pull requests so I know which commits are for which area.

I will try to split out my pull requests in the future so each one can focus on a specific implementation. I will also add a description in the pull request comment instead of combining everything into the title.

> Maybe a more specific name for RoomData, because pictures is room data but you dont have that. etc etc.

Changed variable name to "getRoomBookingData" to be more specific

**Pull request merged**
